version: "3.7"
services:
    db:
        image: postgres:14.2
        container_name: standard_db
        # restart: always
        # TO BE CHANGED
        ports:
            - 9055:5432
        environment:
            POSTGRES_USER: standard
            POSTGRES_PASSWORD: standard
            POSTGRES_HOST_AUTH_METHOD: trust
        volumes:
            - database_data:/var/lib/postgresql/data
            - ./Sarf/init_db.sh:/docker-entrypoint-initdb.d/sarf_init_db.sh
            - ./Core/init_db.sh:/docker-entrypoint-initdb.d/core_init_db.sh
    nginx:
        image: nginx:stable-alpine
        container_name: standard_nginx
        # restart: always
        depends_on:
            - core
        ports:
            - 7000:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            # - ./logs:/var/log/nginx
    core:
        build:
            context: .
            dockerfile: ./Core/dockerfile
        container_name: standard_core
        ports:
            - 7001:7001
        # restart: always
        depends_on:
            - db
            - sarf
        links:
            - db
    sarf:
        build:
            context: .
            dockerfile: ./Sarf/dockerfile
        container_name: standard_sarf
        ports:
            - 7002:7002
        # restart: always
        depends_on:
            - db
        links:
            - db
volumes:
    database_data:
        driver: local
